export const NEWS = {
  REQUEST: 'NEWS_REQUEST',
  SUCCESS: 'NEWS_SUCCESS',
  FAILURE: 'NEWS_FAILURE',
  EDIT_REQUEST: 'NEWS_EDIT_REQUEST',
  EDIT_SUCCESS: 'NEWS_EDIT_SUCCESS',
  EDIT_FAILURE: 'NEWS_EDIT_FAILURE',
};
